package := "{{cookiecutter.package_name}}"

# launch streamlit app
st:
  streamlit run streamlit_app.py

# black and isort
lint:  
   black .
   isort .

# build and show documentation in browser
docs:
  poetry run sphinx-build -a docs docs/site

# how documentation in browser
show:
  start docs/site/index.html

# create rst source for API documentation
apidoc:
  sphinx-apidoc -o docs src/{{ "{{package}}" }}